language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  - SYMFONY_VERSION=v2
  - SYMFONY_VERSION=v3
  - SYMFONY_VERSION=v4

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=v4
    - php: 7.0
      env: SYMFONY_VERSION=v4

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "dunglas/symfony-lock:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-source

script: vendor/bin/phpunit --coverage-clover=coverage.clover